openapi: 3.1.0
info:
  title: ElevenLabs Proxy API
  version: 1.0.0
paths:
  /api/speak:
    post:
      summary: Convert text to speech using ElevenLabs custom voice
      operationId: speak
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Hi, I'm Shindy. Let's practice English!"
      responses:
        "200":
          description: Successful TTS request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "TTS request received successfully!"
                  receivedText:
                    type: string
                    example: "Hi, I'm Shindy. Let's practice English!"
servers:
  - url: https://elevenlabs-proxy-git-main-dmshins-projects.vercel.app
